spring:
  elasticsearch:
#    username: admin
#    password: "!Popash152"
    uris: http://localhost:9200
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: mypassword
    hikari:
      maximum-pool-size: 50          # Было 10 (по умолчанию)
      minimum-idle: 10               # Минимум простаивающих соединений
      connection-timeout: 30000      # 30 секунд на получение соединения
      idle-timeout: 600000           # 10 минут до закрытия простаивающего
      max-lifetime: 1800000
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
        region:
          factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        format_sql: true
      javax:
        cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
#logging:
#  level:
#    org:
##      hibernate:
##        SQL: DEBUG
##        type:
##          descriptor:
##            sql:
##              BasicBinder: TRACE

springdoc:
  operation-id-template: "{className}_{methodName}"
  api-docs:
    enabled: true
    resolve-schema-properties: true
  swagger-ui:
    operations-sorter: method
  writer-with-default-pretty-printer: true
  override-with-generic-response: false
  default-flat-param-object: true
  cache:
    disabled: true
  group-configs:
    - group: default
      paths-to-match: /**
  paths-to-match: /**

app-config:
  files:
    allowed-formats:
      - csv
      - json