/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddressDto,
  AddressGetAllParams,
  AddressGetSearchFields200,
  AddressSearchParams,
  CoordinatesDto,
  CoordinatesGetAllParams,
  CoordinatesGetSearchFields200,
  CoordinatesSearchParams,
  LocationDto,
  LocationGetAllParams,
  LocationGetSearchFields200,
  LocationSearchParams,
  OrganizationDto,
  OrganizationGetAllParams,
  OrganizationGetSearchFields200,
  OrganizationSearchParams,
  PageDtoAddressDto,
  PageDtoCoordinatesDto,
  PageDtoLocationDto,
  PageDtoOrganizationDto,
  PageDtoPersonDto,
  PageDtoProductDto,
  PersonDto,
  PersonGetAllParams,
  PersonGetSearchFields200,
  PersonSearchParams,
  PriceReduceDto,
  ProductDto,
  ProductGetAllParams,
  ProductGetSearchFields200,
  ProductSearchParams,
  ProductoperationsGetRatingCountOfGroups200,
  ProductoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSetBodyItem
} from './model';

export const getOpenAPIDefinition = () => {
/**
 * @summary Получить страницу объектов
 */
const productGetAll = <TData = AxiosResponse<PageDtoProductDto>>(
    params?: ProductGetAllParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/product`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Обновить объект полностью, кроме его ID
 */
const productUpdate = <TData = AxiosResponse<void>>(
    productDto: ProductDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://localhost:8080/api/v1/product`,
      productDto,options
    );
  }

/**
 * @summary Создать объект и получить в ответ его ID
 */
const productCreate = <TData = AxiosResponse<number>>(
    productDto: ProductDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8080/api/v1/product`,
      productDto,options
    );
  }

/**
 * @summary Получить страницу объектов
 */
const personGetAll = <TData = AxiosResponse<PageDtoPersonDto>>(
    params?: PersonGetAllParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/person`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Обновить объект полностью, кроме его ID
 */
const personUpdate = <TData = AxiosResponse<void>>(
    personDto: PersonDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://localhost:8080/api/v1/person`,
      personDto,options
    );
  }

/**
 * @summary Создать объект и получить в ответ его ID
 */
const personCreate = <TData = AxiosResponse<number>>(
    personDto: PersonDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8080/api/v1/person`,
      personDto,options
    );
  }

/**
 * @summary Получить страницу объектов
 */
const organizationGetAll = <TData = AxiosResponse<PageDtoOrganizationDto>>(
    params?: OrganizationGetAllParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/organization`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Обновить объект полностью, кроме его ID
 */
const organizationUpdate = <TData = AxiosResponse<void>>(
    organizationDto: OrganizationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://localhost:8080/api/v1/organization`,
      organizationDto,options
    );
  }

/**
 * @summary Создать объект и получить в ответ его ID
 */
const organizationCreate = <TData = AxiosResponse<number>>(
    organizationDto: OrganizationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8080/api/v1/organization`,
      organizationDto,options
    );
  }

/**
 * @summary Получить страницу объектов
 */
const locationGetAll = <TData = AxiosResponse<PageDtoLocationDto>>(
    params?: LocationGetAllParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/location`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Обновить объект полностью, кроме его ID
 */
const locationUpdate = <TData = AxiosResponse<void>>(
    locationDto: LocationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://localhost:8080/api/v1/location`,
      locationDto,options
    );
  }

/**
 * @summary Создать объект и получить в ответ его ID
 */
const locationCreate = <TData = AxiosResponse<number>>(
    locationDto: LocationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8080/api/v1/location`,
      locationDto,options
    );
  }

/**
 * @summary Получить страницу объектов
 */
const coordinatesGetAll = <TData = AxiosResponse<PageDtoCoordinatesDto>>(
    params?: CoordinatesGetAllParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/coordinates`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Обновить объект полностью, кроме его ID
 */
const coordinatesUpdate = <TData = AxiosResponse<void>>(
    coordinatesDto: CoordinatesDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://localhost:8080/api/v1/coordinates`,
      coordinatesDto,options
    );
  }

/**
 * @summary Создать объект и получить в ответ его ID
 */
const coordinatesCreate = <TData = AxiosResponse<number>>(
    coordinatesDto: CoordinatesDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8080/api/v1/coordinates`,
      coordinatesDto,options
    );
  }

/**
 * @summary Получить страницу объектов
 */
const addressGetAll = <TData = AxiosResponse<PageDtoAddressDto>>(
    params?: AddressGetAllParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/address`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Обновить объект полностью, кроме его ID
 */
const addressUpdate = <TData = AxiosResponse<void>>(
    addressDto: AddressDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://localhost:8080/api/v1/address`,
      addressDto,options
    );
  }

/**
 * @summary Создать объект и получить в ответ его ID
 */
const addressCreate = <TData = AxiosResponse<number>>(
    addressDto: AddressDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8080/api/v1/address`,
      addressDto,options
    );
  }

const productoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSet = <TData = AxiosResponse<ProductDto[]>>(
    productoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSetBodyItem: ProductoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSetBodyItem[], options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8080/api/v1/product/unitOfMeasure/productWhereUnitOfMeasureIsSet`,
      productoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSetBodyItem,options
    );
  }

const productoperationsReducePrice = <TData = AxiosResponse<void>>(
    priceReduceDto: PriceReduceDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8080/api/v1/product/price/reduce`,
      priceReduceDto,options
    );
  }

/**
 * @summary Получить объект по id
 */
const productGetById = <TData = AxiosResponse<ProductDto>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/product/${id}`,options
    );
  }

/**
 * @summary Удалить объект по ID
 */
const productDelete = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:8080/api/v1/product/${id}`,options
    );
  }

/**
 * @summary Получить страницу объектов с заданным значением поля
 */
const productSearch = <TData = AxiosResponse<PageDtoProductDto>>(
    params: ProductSearchParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/product/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Получить список разрешенных полей для поиска
 */
const productGetSearchFields = <TData = AxiosResponse<ProductGetSearchFields200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/product/search/fields`,options
    );
  }

const productoperationsGetRatingSum = <TData = AxiosResponse<number>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/product/rating/sum`,options
    );
  }

const productoperationsGetRatingCountOfProductWhereRatingGreaterThat = <TData = AxiosResponse<number>>(
    rating: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/product/rating/countOfProductWhereRatingGreaterThan/${rating}`,options
    );
  }

const productoperationsGetRatingCountOfGroups = <TData = AxiosResponse<ProductoperationsGetRatingCountOfGroups200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/product/rating/countOfGroups`,options
    );
  }

/**
 * @summary Получить объект по id
 */
const personGetById = <TData = AxiosResponse<PersonDto>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/person/${id}`,options
    );
  }

/**
 * @summary Удалить объект по ID
 */
const personDelete = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:8080/api/v1/person/${id}`,options
    );
  }

/**
 * @summary Получить страницу объектов с заданным значением поля
 */
const personSearch = <TData = AxiosResponse<PageDtoPersonDto>>(
    params: PersonSearchParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/person/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Получить список разрешенных полей для поиска
 */
const personGetSearchFields = <TData = AxiosResponse<PersonGetSearchFields200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/person/search/fields`,options
    );
  }

/**
 * @summary Получить объект по id
 */
const organizationGetById = <TData = AxiosResponse<OrganizationDto>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/organization/${id}`,options
    );
  }

/**
 * @summary Удалить объект по ID
 */
const organizationDelete = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:8080/api/v1/organization/${id}`,options
    );
  }

/**
 * @summary Получить страницу объектов с заданным значением поля
 */
const organizationSearch = <TData = AxiosResponse<PageDtoOrganizationDto>>(
    params: OrganizationSearchParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/organization/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Получить список разрешенных полей для поиска
 */
const organizationGetSearchFields = <TData = AxiosResponse<OrganizationGetSearchFields200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/organization/search/fields`,options
    );
  }

/**
 * @summary Получить объект по id
 */
const locationGetById = <TData = AxiosResponse<LocationDto>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/location/${id}`,options
    );
  }

/**
 * @summary Удалить объект по ID
 */
const locationDelete = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:8080/api/v1/location/${id}`,options
    );
  }

/**
 * @summary Получить страницу объектов с заданным значением поля
 */
const locationSearch = <TData = AxiosResponse<PageDtoLocationDto>>(
    params: LocationSearchParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/location/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Получить список разрешенных полей для поиска
 */
const locationGetSearchFields = <TData = AxiosResponse<LocationGetSearchFields200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/location/search/fields`,options
    );
  }

/**
 * @summary Получить объект по id
 */
const coordinatesGetById = <TData = AxiosResponse<CoordinatesDto>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/coordinates/${id}`,options
    );
  }

/**
 * @summary Удалить объект по ID
 */
const coordinatesDelete = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:8080/api/v1/coordinates/${id}`,options
    );
  }

/**
 * @summary Получить страницу объектов с заданным значением поля
 */
const coordinatesSearch = <TData = AxiosResponse<PageDtoCoordinatesDto>>(
    params: CoordinatesSearchParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/coordinates/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Получить список разрешенных полей для поиска
 */
const coordinatesGetSearchFields = <TData = AxiosResponse<CoordinatesGetSearchFields200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/coordinates/search/fields`,options
    );
  }

/**
 * @summary Получить объект по id
 */
const addressGetById = <TData = AxiosResponse<AddressDto>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/address/${id}`,options
    );
  }

/**
 * @summary Удалить объект по ID
 */
const addressDelete = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:8080/api/v1/address/${id}`,options
    );
  }

/**
 * @summary Получить страницу объектов с заданным значением поля
 */
const addressSearch = <TData = AxiosResponse<PageDtoAddressDto>>(
    params: AddressSearchParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/address/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Получить список разрешенных полей для поиска
 */
const addressGetSearchFields = <TData = AxiosResponse<AddressGetSearchFields200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/api/v1/address/search/fields`,options
    );
  }

return {productGetAll,productUpdate,productCreate,personGetAll,personUpdate,personCreate,organizationGetAll,organizationUpdate,organizationCreate,locationGetAll,locationUpdate,locationCreate,coordinatesGetAll,coordinatesUpdate,coordinatesCreate,addressGetAll,addressUpdate,addressCreate,productoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSet,productoperationsReducePrice,productGetById,productDelete,productSearch,productGetSearchFields,productoperationsGetRatingSum,productoperationsGetRatingCountOfProductWhereRatingGreaterThat,productoperationsGetRatingCountOfGroups,personGetById,personDelete,personSearch,personGetSearchFields,organizationGetById,organizationDelete,organizationSearch,organizationGetSearchFields,locationGetById,locationDelete,locationSearch,locationGetSearchFields,coordinatesGetById,coordinatesDelete,coordinatesSearch,coordinatesGetSearchFields,addressGetById,addressDelete,addressSearch,addressGetSearchFields}};
export type ProductGetAllResult = AxiosResponse<PageDtoProductDto>
export type ProductUpdateResult = AxiosResponse<void>
export type ProductCreateResult = AxiosResponse<number>
export type PersonGetAllResult = AxiosResponse<PageDtoPersonDto>
export type PersonUpdateResult = AxiosResponse<void>
export type PersonCreateResult = AxiosResponse<number>
export type OrganizationGetAllResult = AxiosResponse<PageDtoOrganizationDto>
export type OrganizationUpdateResult = AxiosResponse<void>
export type OrganizationCreateResult = AxiosResponse<number>
export type LocationGetAllResult = AxiosResponse<PageDtoLocationDto>
export type LocationUpdateResult = AxiosResponse<void>
export type LocationCreateResult = AxiosResponse<number>
export type CoordinatesGetAllResult = AxiosResponse<PageDtoCoordinatesDto>
export type CoordinatesUpdateResult = AxiosResponse<void>
export type CoordinatesCreateResult = AxiosResponse<number>
export type AddressGetAllResult = AxiosResponse<PageDtoAddressDto>
export type AddressUpdateResult = AxiosResponse<void>
export type AddressCreateResult = AxiosResponse<number>
export type ProductoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSetResult = AxiosResponse<ProductDto[]>
export type ProductoperationsReducePriceResult = AxiosResponse<void>
export type ProductGetByIdResult = AxiosResponse<ProductDto>
export type ProductDeleteResult = AxiosResponse<void>
export type ProductSearchResult = AxiosResponse<PageDtoProductDto>
export type ProductGetSearchFieldsResult = AxiosResponse<ProductGetSearchFields200>
export type ProductoperationsGetRatingSumResult = AxiosResponse<number>
export type ProductoperationsGetRatingCountOfProductWhereRatingGreaterThatResult = AxiosResponse<number>
export type ProductoperationsGetRatingCountOfGroupsResult = AxiosResponse<ProductoperationsGetRatingCountOfGroups200>
export type PersonGetByIdResult = AxiosResponse<PersonDto>
export type PersonDeleteResult = AxiosResponse<void>
export type PersonSearchResult = AxiosResponse<PageDtoPersonDto>
export type PersonGetSearchFieldsResult = AxiosResponse<PersonGetSearchFields200>
export type OrganizationGetByIdResult = AxiosResponse<OrganizationDto>
export type OrganizationDeleteResult = AxiosResponse<void>
export type OrganizationSearchResult = AxiosResponse<PageDtoOrganizationDto>
export type OrganizationGetSearchFieldsResult = AxiosResponse<OrganizationGetSearchFields200>
export type LocationGetByIdResult = AxiosResponse<LocationDto>
export type LocationDeleteResult = AxiosResponse<void>
export type LocationSearchResult = AxiosResponse<PageDtoLocationDto>
export type LocationGetSearchFieldsResult = AxiosResponse<LocationGetSearchFields200>
export type CoordinatesGetByIdResult = AxiosResponse<CoordinatesDto>
export type CoordinatesDeleteResult = AxiosResponse<void>
export type CoordinatesSearchResult = AxiosResponse<PageDtoCoordinatesDto>
export type CoordinatesGetSearchFieldsResult = AxiosResponse<CoordinatesGetSearchFields200>
export type AddressGetByIdResult = AxiosResponse<AddressDto>
export type AddressDeleteResult = AxiosResponse<void>
export type AddressSearchResult = AxiosResponse<PageDtoAddressDto>
export type AddressGetSearchFieldsResult = AxiosResponse<AddressGetSearchFields200>
