/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * объект
 */
export interface LocationDto {
  id: number;
  x?: number;
  y?: number;
  z?: number;
}
