/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrganizationDto } from './organizationDto';

export interface PageDtoOrganizationDto {
  content?: OrganizationDto[];
  pageNumber?: number;
  pageSize?: number;
  totalSize?: number;
}
