/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PersonDto } from './personDto';

export interface PageDtoPersonDto {
  content?: PersonDto[];
  pageNumber?: number;
  pageSize?: number;
  totalSize?: number;
}
