/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductDto } from './productDto';

export interface PageDtoProductDto {
  content?: ProductDto[];
  pageNumber?: number;
  pageSize?: number;
  totalSize?: number;
}
