/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CoordinatesDto } from './coordinatesDto';

export interface PageDtoCoordinatesDto {
  content?: CoordinatesDto[];
  pageNumber?: number;
  pageSize?: number;
  totalSize?: number;
}
