/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AddressDto } from './addressDto';

export interface PageDtoAddressDto {
  content?: AddressDto[];
  pageNumber?: number;
  pageSize?: number;
  totalSize?: number;
}
