/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LocationDto } from './locationDto';

export interface PageDtoLocationDto {
  content?: LocationDto[];
  pageNumber?: number;
  pageSize?: number;
  totalSize?: number;
}
