/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSetBodyItem = typeof ProductoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSetBodyItem[keyof typeof ProductoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSetBodyItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductoperationsGetUnitOfMeasureProductWhereUnitOfMeasureIsSetBodyItem = {
  METERS: 'METERS',
  CENTIMETERS: 'CENTIMETERS',
  LITERS: 'LITERS',
  GRAMS: 'GRAMS',
  MILLIGRAMS: 'MILLIGRAMS',
} as const;
